api/issue.js

Fix assignIssue to allow `null` to unassign a user in api/issue

---

README.md
api/projectCategory.js
index.js

New client that retrieves list of project categories.
I use that for filtering issues based on project categories, not only project. Maybe helpful for others

projectCategory client

---

index.js

enabling to use the original response from jira-api for more flexibility

add response to API-callback

---

api/worklog.js
index.js

I added support for the worklog REST endpoints from Atlassian.  It would be appreciated if they were merged into the main branch and npm updated.

Added support for the worklog endpoints

---

api/user.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/floralvikings/jira-connector/30)

added expand parameter to getUser

---

api/user.js

This PR will address this issue https://github.com/floralvikings/jira-connector/issues/32

Fix user expand

---

README.md
api/board.js
index.js

Just the basics for some Agile data

Add initial support for calls to Agile API

---

api/project.js
api/search.js

Added createProject, deleteProject, getProjectProperties as well as changed to use GET instead of POST for search as it then can take expand and other parameters

added methods to project.js as well as more detailed search

---

index.js

Fix webhook API endpoint

---

README.md
api/board.js

Adding method for getting sprints for a specific board.

Adding getSprintsForBoard to board methods

---

api/search.js

Atlassian recently (and finally!!) added the ability to get full property definitions on searches. This will allow us to get them!

Added Full Property Retrieval to Search

---

api/board.js

"name" and "projectKeyOrId" are added as described as following.
https://docs.atlassian.com/jira-software/REST/7.3.1/#agile/1.0/board-getAllBoards

Add query parameter for AgileBoardClient.getAllBoards()

---

README.md
api/group.js
api/issueType.js
api/permission-scheme.js
api/permissions.js
api/roles.js
index.js

Changelog:
------------------------------------------------------------------------------- 
Clients added:
1. PermissionsClient
2. PermissionSchemeClient
3. RoleClient
Clients updated:
1. GroupClient
2. IssueTypeClient
They cover all the stable REST API endpoints listed below:
Permissions
1. GET /rest/api/2/permissions
PermissionScheme
1. GET /rest/api/2/permissionscheme
2. POST /rest/api/2/permissionscheme
3. GET /rest/api/2/permissionscheme/{schemeId}
4. PUT /rest/api/2/permissionscheme/{schemeId}
5. DELETE /rest/api/2/permissionscheme/{schemeId}
6. GET /rest/api/2/permissionscheme/{schemeId}/permission
7. POST /rest/api/2/permissionscheme/{schemeId}/permission
8. GET /rest/api/2/permissionscheme/{schemeId}/permission/{permissionId}
9. DELETE …

Added Permission client, PermissionScheme and Role Client

---

api/board.js
api/epic.js
api/version.js

fixed board.js/getBoard
added epic.js with function "getIssuesForEpic"

fixed "getBoard" function of board.js & added epic.js to get issues of an specific epic

---

api/board.js

For instance to get the `renderedFields` for each issue from the board

Add expand query param to getIssuesForBoard

---

api/board.js

Added `fields` option for [Get issues for board](https://developer.atlassian.com/cloud/jira/software/rest/#api-rest-agile-1-0-board-boardId-issue-get)

Board api updated

---

README.md
api/labels.js
index.js

use this API to retrieve all the available labels.
**e.g.** Labels are necessary for fill the label field in issue creation

feat: Added Labels API

---

README.md
api/backlog.js
api/epic.js
index.js

Added API for [backlog](https://developer.atlassian.com/cloud/jira/software/rest/#api-group-Backlog)

Added backlog API

---

README.md
api/board.js

Added a few endpoints for [board](https://developer.atlassian.com/cloud/jira/software/rest/#api-group-Board)

Added a few endpoints for board.js

---

index.js

Some API's returns `3XX` codes as response code. 
Example: https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-api-3-field-fieldKey-option-optionId-issue-delete
Correct me if i'm suddenly wrong

Handled 3XX response codes

---

api/dashboard.js

Dashboard opts marked as optional

---

api/auth.js

Fixed broken URL for auth API

---

api/auth.js

Typo fixed

---

api/issue.js

Fixes for issue transition

---

api/search.js

Fixes for search.search

---

api/project.js

Fixes for getAllProjects

---

README.md
api/epic.js

Epic API added

---

api/issue.js
package-lock.json
package.json

addAttachment fixes

---

index.js

Fixes for #141 and mayby for #132
Test required. Please install with this command: `npm i https://github.com/floralvikings/jira-connector.git#features/sslStrict`
Code for test:
```js
const jira = new JiraClient({
protocol: 'https',
host: '',
username: '',
password: '',
apiVersion: '2',
strictSSL: false
})
```

Added strictSSL option

---

api/epic.d.ts
index.d.ts
index.js
package.json

Basic types definitions added

---

api/issue.d.ts
api/issue.js
index.d.ts

Fixes for issue worklog

---

api/board.js

When I tried to get issues for the sprint, I got an error. I just added missing params.

[fix]: Add missing params in getIssuesForSprint function

---

README.md

Typescript indication in README

---

api/issue.d.ts

Fixed typo in issue.d.ts

---

api/issue.js

I found some issues with incorrect paths for endpoints.
Also there was missed X-Atlassian-Token:nocheck for attachment uploading
Would be cool if you will release it ASAP :)
Thanks

Fix some issues with API paths and fix attachment uploading

---

api/issue.js

`worklog` option added for `issue.addWorklog` #106

Added worklog option

---

api/project.d.ts
api/project.js
index.d.ts

Update project method added

---

index.js

Fixes for strictSSL

---

README.md
api/issue.d.ts
api/issue.js

Expose https://developer.atlassian.com/cloud/jira/platform/rest/v2/#api-rest-api-2-issue-issueIdOrKey-changelog-get

Get issue changelog

---

README.md
api/project.d.ts
api/project.js

Deprecation warning removed

---

api/project.d.ts

resolution for https://github.com/floralvikings/jira-connector/issues/182

fixed ts support with noImplicitAny flag

---

README.md
api/user.d.ts
api/user.js
index.d.ts

Fix for issue https://github.com/floralvikings/jira-connector/issues/180

added users/search endpoint

---

api/board.d.ts
api/board.js
api/user.js
index.js

#179 Property added as body for setBoardProperty

---

api/issue.d.ts
api/issue.js

Issue updates fixes

---

api/project.d.ts
api/project.js

gelAllProjects version choosing added

---

api/user.d.ts
api/user.js

accountId property added

---

api/board.d.ts

I'm exploring using the JIRA api for things, and I'd like to do so w/ TypeScript, so I'm going to incrementally expand the typings as I go if that's ok 😄
This is the first nice thing I've confirmed - even if it's incorrect, it can be improved via PR 🙂

Define JiraBoard interface & return of getBoard

---

api/issueType.d.ts
api/issueType.js
index.d.ts

Add basic type definitions for issueType api

---

api/application-properties.js
types/api/applicationProperties.d.ts
types/api/index.d.ts
types/index.d.ts

@G-Rath can you please review this PR?

Added types for application properties

---

api/search.js

Unrecognized field "fieldsByKeys" fixed

---

README.md
api/labels.js
types/api/index.d.ts
types/api/labels.d.ts
types/index.d.ts
types/models/index.d.ts
types/models/labels/index.d.ts

getAllLabels added

---

types/api/applicationProperties.d.ts
types/api/attachment.d.ts
types/api/backlog.d.ts
types/api/board.d.ts
types/api/epic.d.ts
types/api/issue.d.ts
types/api/issueType.d.ts
types/api/labels.d.ts
types/api/project.d.ts
types/api/search.d.ts
types/api/sprint.d.ts
types/api/user.d.ts
types/api/version.d.ts
types/models/temp.d.ts

fixes  https://github.com/floralvikings/jira-connector/issues/225

Fix typescript imports

---

README.md
api/developmentInformation.js
index.js
types/api/developmentInformation.d.ts
types/api/index.d.ts
types/index.d.ts

fixes #228
I just copied this from my [library](https://github.com/MrRefactoring/jira-api-wrapper)

Added development information API
