README.md, index.js
In this small PR, I added the possibility to use a Cookie Jar for all the requests.
I find it convenient since when using `jira-connector`, one can prompt the user only once for its username & password, and then store the cookie in a file for example.
All the following requests would just use the created cookie. Like that, the user won't have to store its password, are re-type it everytime, or the developer won't have to go through the pain of implementing an OAuth Authentication.
I also updated the README with an example, and the JS-DocBlock :)
=> Be able to use a Cookie Jar

README.md
The s/oauth_verified/oauth_verifier/ swap had me confused for a while ;)
=> Fix typos in OAuth example

README.md, index.js
Thought this would be a worthy addition (I'm currently using it to base64 my creds with shared repo because I just don't feel like setting up oauth on my project at the moment nor sharing my creds openly in a file).
https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-basic-authentication
=> Add Base64 basic_auth support

api/workflow.js
This will allow a user to get a list of all workflows (not previously permitted) OR details of a specific workflow.
=> Make workflow name optional

api/issue.js
The documentation specifies that "Fields will only be returned if ```expand=projects.issuetypes.fields.```" but we didn't have a way to specify that with jira-connector API. So, I've simply added that option so that it can be added to the query string.
Thanks for your great work on this module!
=> Added the expand option to createmeta

index.js, lib/oauth_util.js
We have Jira hosted at "/jira/" and reverse-proxied, this PR allows it to exist somewhere other than "/" by setting a "path_prefix" config field when instantiating the JiraClient (and when doing the OAuth calls).
=> Allow Jira to exist somewhere other than "/" in the URL

lib/oauth_util.js
The prefix breaks the request for the Oauth token, just leave it empty and all is fine.
=> Remove slash from prefix

api/issue.js
https://docs.atlassian.com/jira/REST/6.4/
/rest/api/2/issue/{issueIdOrKey}/comment/{id}
requires as payload:
```
{ body: comment }
```
The same with REST 7.0
=> Fix: issue.addComment - wrap opts.comment in {body: comment}

api/issue.js
With Jira v7.2.0 ([this issue](https://jira.atlassian.com/browse/JRA-34423)), you now have the ability to decide whether or not to notify users when you edit an issue through the api. To use this feature, a request needs to be made similar to the following:
`http://jrl2014s:8080/rest/api/2/issue/TEST-9?notifyUsers=false`
To resolve this, we need to pass in a value to the `qs` parameter of the `buildRequestOptions` function. This allows us to make api calls like so:
```javascript
jira.issue.editIssue({issue: {update: {labels: [{add: 'blocked'}]}}, qs: { notifyUsers: false }, issueKey: 'TEST-9'})
```
=> added support for query string fields on issues

README.md, api/webhook.js, index.js
This PR adds support for the separate API used to view, create, and delete webhooks on Jira.
=> Add support for webhooks API

index.js
Wrapping the JSON.parse within the jira connector's response handling so that invalid JSON responses do not trigger unhandled exceptions
PTAL @floralvikings 
CC @vaskevich
=> Catching JSON.parse errors within responses

api/issue.js
I'm not sure how long this has been possible with JIRA's API but it's very useful for pulling in data/values created by some plug-ins added to projects. Works exactly the same as `fields`.
Been using it for a few days in my own production environment and works perfectly.
=> Added ability to get properties on issue fetch

api/project.js
This PR uses the options parameter passed to getAllProjects - it is needed for the expanded option
=> use options for getAllProjects

api/board.js
just adding an implementation for getting backlog issues for a given boardId as seen here:
https://docs.atlassian.com/jira-software/REST/cloud/#agile/1.0/board-getIssuesForBacklog
=> Adding getIssuesForBacklog agile api method

api/board.js
When listing the sprints for an agile board, the JIRA API supports filtering by sprint state. This PR exposes that functionality.
=> Optionally filter board sprints by state

api/board.js, api/filter.js, api/issue.js, api/myPermissions.js, api/myself.js, api/search.js, index.js, package.json
Added "jql" and "fields" options for "getIssuesForBoard" method. Since this method using GET request, for Oauth signature we need to use "useQuerystring" option of request package to stringify fields list correctly.
=> expande getIssuesForBoard + useQuerystring for fixing oauth get request

README.md
Worklog endpoint is already supported but the information is missing in readme.
=> doc: added worklog endpoint to readme

README.md, api/issue.js
Added support for getIssuePickerResource API call - returns suggested issues which match an auto-completion query
https://docs.atlassian.com/software/jira/docs/api/REST/7.6.1/#api/2/issue-getIssuePickerResource
=> Added getIssuePicker method

package.json
The way the package is currently configured, the docs/ directory is distributed with the packaged npm. This means that all projects that include jira-connector as a dependency will bundle the compiled HTML docs for all previous versions of jira-connector, too, which causes the package's bundled size to increase by roughly a factor of 100x.
Before this change:
```
$ npm pack
...
npm notice === Tarball Details ===
npm notice name:          jira-connector
npm notice version:       2.9.0
npm notice filename:      jira-connector-2.9.0.tgz
npm notice package size:  5.1 MB
npm notice unpacked size: 23.5 MB
npm notice shasum:        b1381446a9a337be1e9248723fd3cc92f7fed487
npm notice integrity:     sha512-VMQ7fGpY/HBYJ[...]wLAP2LmobCU7Q==
npm notice total files:   1167
```
After this change:
``` …
```
=> Exclude docs/ from packaged npm

api/board.js
Fixed error with optional option `field` in #118
=> Fixed optional field option

README.md, api/board.js
The method maps to the following API call: https://developer.atlassian.com/cloud/jira/software/rest/#api-rest-agile-1-0-board-boardId-reports-get
=> Add getReportsForBoard method

api/issue.js
Assigning issue with name is removed from JIRA API , changed to accountId.
[deprecation-notice-user-privacy-api-migration-guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/)
Verified the changes , its working fine
=> added changes for assgin issue api  params WRT JIRA REST API changes

api/issue.d.ts, api/issue.js
Fixes for #161.
@liemnt tests required:
Install:
```bash
npm i https://github.com/floralvikings/jira-connector.git#custom-headers-for-attachment
```
Test method:
```js
jiraClient.issue.addAttachment({
...
headers: {
'X-Atlassian-Token': 'nocheck'
}
});
```
=> Custom headers allowed for addAttachment method

README.md
I'm testing the basic authentication with basic token and I'm seeing errors like so below:
2019-06-25T13:09:40.232Z	807fc98a-bb25-48a1-9e40-423d5d4215fe	Error: Missing 'api_token' property.
at new module.exports (/var/task/node_modules/jira-connector/index.js:194:23)
at module.exports.jiratest (/var/task/handler.js:22:14)
I checked the code and it is indeed looking for 'api_token' instead of 'token'
Theres two ways to change this, either change the code or change the readme, I chose the easier route.
=> Changed token object name to api_token.

api/sprint.d.ts, api/sprint.js, index.d.ts
Basic type definitions for `sprint`. Also adjusted the JSDocs, and renamed `swapped` parameter of `#swapSprint` to `opts` for consistency.
=> Add basic type definitions for sprint api

api/webhook.js
The webhook part of this lib uses the 1.0 version REST APIs. The 1.0 version of the `createWebhook` API  doesn't return a `webhookId`, but a `self` field that includes the entire URI. This PR makes it possible to use that in other calls so one doesn't have to parse the `webhookId` out of the URI.
=> add webhookURI to opts in webhook apis
